### ISSUE TITLE
Exam Connection Tests

### ISSUE THREAD

**Issue by NikoBergemann** [upb-uc4/hlf-api#163]
Tests for new Exam Connection
**Required finished Issues**
- [x] HLF-CHAINCODE Exam https://github.com/upb-uc4/hlf-chaincode/issues/155
- [x] HLF-API-ExamConnection https://github.com/upb-uc4/hlf-api/issues/162

**Tasks**
- [x] implement test
- [x] check pipeline / fix chaincode
