### ISSUE TITLE
ExamAdmission Connection Tests

### ISSUE THREAD

**Issue by NikoBergemann** [upb-uc4/hlf-api#165]
Tests for changed AdmissionConnection
**Required finished Issues**
- [x] HLF-CHAINCODE ExamAdmission https://github.com/upb-uc4/hlf-chaincode/issues/156
- [x] HLF-API-AdmissionConnection https://github.com/upb-uc4/hlf-api/issues/164

**Tasks**
- [x] implement test
- [x] check pipeline / fix chaincode
