### ISSUE TITLE
Exam Performance Connection

### ISSUE THREAD

**Issue by NikoBergemann** [upb-uc4/hlf-api#167]
Tests for new ExamPerformanceConnection

**Required finished Issues**
- [ ] HLF-CHAINCODE ExamAdmission https://github.com/upb-uc4/hlf-chaincode/issues/157
- [ ] HLF-API-AdmissionConnection https://github.com/upb-uc4/hlf-api/issues/165

**Tasks**
- [ ] implement test
- [ ] check pipeline / fix chaincode
